[CELL-99] - Troposphere Port

diff --git a/cell b/cell
--- a/cell
+++ b/cell
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+
 # cell-os cli
 type aws >/dev/null 2>&1 || { echo >&2 "AWS CLI not found
 pip install awscli or brew install awscli
@@ -7,7 +8,6 @@ see http://docs.aws.amazon.com/cli/latest/userguide/installing.html"; exit 1;}
 
 SAASBASE_ACCESS_KEY_ID='XXXXXXXXXXXXXXXXXXXX'
 SAASBASE_SECRET_ACCESS_KEY='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
-CF_TEMPLATE_PATH='./deploy/aws/elastic-cell.json'
 AWS_OPTIONS='--output text'
 PROXY_PORT=${PROXY_PORT:-'1234'}
 SSH_TIMEOUT=${SSH_TIMEOUT:-'5'}
@@ -186,6 +186,23 @@ if [[ "${action}" == "scale" ]]; then
  exit
 fi
 
+if [[ "${action}" == "sshall" ]]; then
+  ssh_options="-o ConnectTimeout=${SSH_TIMEOUT}"
+  machines=$(for role in nucleus stateful-body membrane stateless-body; do 
+    aws ${AWS_OPTIONS} ec2 describe-instances \
+      --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
+      --filters Name=instance-state-code,Values=16 \
+      Name=tag:cell,Values=${cell_name} Name=tag:role,Values=${role} 
+  done | sed 's/$/,/g' | tr -d "\n" | sed 's/,$//g')
+
+  key_file=${KEYPATH:-"${HOME}/.ssh"}/${AWS_KEY_PAIR}.pem
+  if ! [[ -e "${key_file}" ]]; then
+    echo "can't find ${key_file}. Set your KEYPATH env var to the .pem location"
+    exit 1
+  fi
+  i2cssh -l ${SSH_USER} -m $machines -Xi="${key_file}"
+fi
+
 if [[ "${action}" == "ssh" || "${action}" == "log" || "${action}" == "cmd" 
   || "${action}" == "proxy" ]]; then
 
@@ -251,8 +268,19 @@ if [[ "${action}" == "ssh" || "${action}" == "log" || "${action}" == "cmd"
 fi
 
 if [[ "${action}" == "create" ]]; then
-  echo "creating s3 bucket s3://${BUCKET_NAME}"
-  RET=$({ aws s3 mb "s3://${BUCKET_NAME}" ;} 2>&1)
+  if [[ $GENERATE ]]; then
+    echo "creating stacks"
+    python $DIR/deploy/aws/tools/elastic-cell.py > $DIR/deploy/aws/tools/elastic-cell.json
+    python $DIR/deploy/aws/tools/elastic-cell-scaling-group.py > $DIR/deploy/aws/tools/elastic-cell-scaling-group.json
+    
+    base_stack=$DIR/deploy/aws/tools/elastic-cell.json
+    sub_stack=$DIR/deploy/aws/tools/elastic-cell-scaling-group.json
+  else
+    base_stack=$DIR/deploy/aws/elastic-cell.json
+    sub_stack=$DIR/deploy/aws/elastic-cell-scaling-group.json
+  fi
+  echo "creating s3 bucket s3://${bucket_name}"
+  RET=$({ aws s3 mb "s3://${bucket_name}" ;} 2>&1)
   create_error=$?
   echo ${RET} | grep AlreadyOwnedByYou > /dev/null
   already_owned=$?
@@ -270,7 +298,7 @@ if [[ "${action}" == "create" ]]; then
 
   echo "creating stack ${STACK_NAME}..."
   aws cloudformation create-stack \
-      --template-body "file://${CF_TEMPLATE_PATH}" \
+      --template-body "file://${base_stack}" \
       --stack-name "${STACK_NAME}" \
       --tags Key=name,Value="${cell_name}" Key=version,Value="${VERSION}" \
       --capabilities CAPABILITY_IAM \
