[CELL-53] - cell-cli node index is ignored

diff --git a/cell b/cell
--- a/cell
+++ b/cell
@@ -157,16 +157,17 @@ if [[ $action == "ssh" || $action == "log" || $action == "cmd" || $action == "pr
   fi
   role=$3
 
-  ip_and_keypair=$(aws ec2 describe-instances --query 'Reservations['$index'].Instances[0].[PublicIpAddress, KeyName]' --filters Name=instance-state-code,Values=16 Name=tag:cell,Values=${cell_name} Name=tag:role,Values=${role})
-  if [ "$ip_and_keypair" == "None" ]; then
-    echo "can't find host yet. Is the cell fully up?"
-    exit 1
-  fi
-
-
   index=$4
   if [[ -z $index || -n ${index//[0-9]/} ]]; then
     index=0
+  fi
+
+  ip_and_keypair=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[PublicIpAddress, KeyName]' \
+    --filters Name=instance-state-code,Values=16 Name=tag:cell,Values=${cell_name} Name=tag:role,Values=${role} \
+    | sed -n "${index} p")
+  if [[ "$ip_and_keypair" == "None" || -z "$ip_and_keypair" ]]; then
+    echo "can't find node ${index} in ${role} yet. Is the cell fully up?"
+    exit 1
   fi
 
   if [[ $action == "cmd" &&  -z $5 ]]; then
