[CELL-529] - HDFS provisioning can fail but trigger success

diff --git a/deploy/seed/10-hdfs-raw/provision_post b/deploy/seed/10-hdfs-raw/provision_post
--- a/deploy/seed/10-hdfs-raw/provision_post
+++ b/deploy/seed/10-hdfs-raw/provision_post
@@ -36,7 +36,19 @@ if [[ -f /opt/cell/etc/roles/nucleus ]]; then
   aws s3api put-object --bucket ${cell_bucket_name} --key ${full_cell_name}/shared/setup/${aws_parent_stack_name}/zk/$host
   if [[ $host == $nn1_host ]]; then
     aws_wait "aws s3api list-objects --bucket ${cell_bucket_name} --prefix ${full_cell_name}/shared/setup/${aws_parent_stack_name}/zk/" ".Contents | length" "3"
-    su --login hadoop -c "/home/hadoop/hadoop/bin/hdfs namenode -format -nonInteractive"
+    su --login hadoop -c "/home/hadoop/hadoop/bin/hdfs namenode -format -nonInteractive" &> hdfs-format-result
+    format_successful=$?
+    if [[ format_successful -eq 1 ]]; then
+        # check if already formatted or otherwise fail
+        grep -q "Running in non-interactive mode, and data appears to exist in Storage Directory" hdfs-format-result
+        if [[ $? -ne 0 ]]; then
+            cat hdfs-format-result
+            exit 1 # provision script will mark as failed and retry
+        fi
+    fi
+
+    # this only "formats" the zookeeper hadoop-ha dir if it doesn't exist
+    # hence it would only fail if zk is down
     su --login hadoop -c "/home/hadoop/hadoop/bin/hdfs zkfc -formatZK -nonInteractive"
     systemctl start hadoop-hdfs-zkfc
     systemctl start hadoop-hdfs-namenode
