[CELL-515] - Remove AWS specific commands from seed / machine setup scripts

diff --git a/deploy/machine/cloud-config b/deploy/machine/cloud-config
--- a/deploy/machine/cloud-config
+++ b/deploy/machine/cloud-config
@@ -13,11 +13,12 @@ runcmd:
 mounts: 
   - [ ephemeral0, None ]
 write_files:
-  - path: /usr/local/bin/local_wait
+  - path: /usr/local/bin/cmdwait
     owner: 'root:root'
     permissions: '0755'
     content: |
       #!/bin/bash
+      # executes a command ($1) until its output is equal to the target ($2)
       [[ $# = 2 ]] || { echo "Internal error calling wait-for" ; exit 99 ; }
       cmd=$1
       target=$2
@@ -33,32 +34,12 @@ write_files:
           loop=$(( $loop + 1 ))
       done
       exit 1
-  - path: /usr/local/bin/aws_wait
-    owner: 'root:root'
-    permissions: '0755'
-    content: |
-      #!/bin/bash
-      [[ $# = 3 ]] || { echo "Internal error calling wait-for" ; exit 99 ; }
-      cmd=$1
-      pattern=$2
-      target=$3
-      loop=1
-      echo "Waiting for $cmd | jq \"$pattern\""
-      while [[ $loop -le 200 ]]; do
-          STATE=$($cmd | jq "$pattern")
-          if [[ "$STATE" == "$target" ]]; then
-              exit 0
-          fi
-          sleep 5
-          printf "."
-          loop=$(( $loop + 1 ))
-      done
-      exit 1
   - path: /usr/local/bin/zk-list-nodes
     owner: 'root:root'
     permissions: '0755'
     content: |
       #!/bin/bash
+      #list the zookeeper nodes, making sure that we have at least 3
       source /etc/profile.d/cellos.sh
       num_servers=${num_servers:-3}
       code=$(curl -s -o /dev/null -w "%{http_code}" ${zk_cluster_list})
@@ -85,8 +66,8 @@ write_files:
     permissions: '0755'
     content: |
       #!/bin/bash
+      #blocks execution until we have a ZK quorum
       source /etc/profile.d/cellos.sh
-      ### Block until we have a ZK quorum
       num_servers=3
       while true; do
         code=$(curl -H "Accept: application/json" -s -o /dev/null -w "%{http_code}" "${zk_base_url}/cluster/status")
@@ -123,8 +104,7 @@ write_files:
     permissions: '0755'
     content: |
       #!/bin/bash
-      # provision script
-      # provisioner puppet role1,role2,role3
+      # executes a provision command with retries on failure
       source /etc/profile.d/cellos.sh
 
       provision_with_retry() {
@@ -147,7 +127,6 @@ write_files:
         done
       }
 
-
       if [[ $1 == "puppet" ]]; then
           shift
           AWS_ACCESS_KEY_ID="${SAASBASE_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${SAASBASE_SECRET_ACCESS_KEY}" \
@@ -158,61 +137,56 @@ write_files:
     permissions: '0755'
     content: |
       #!/bin/bash
+      #detects and mounts /dev/sdx disks on an instance
       source /etc/profile.d/cellos.sh
-      deviceslist=('/dev/xvdb' '/dev/xvdc' '/dev/xvdd' '/dev/xvde' '/dev/xvdf' '/dev/xvdg' '/dev/xvdh' '/dev/xvdi' '/dev/xvdj' '/dev/xvdk' '/dev/xvdl' '/dev/xvdm' '/dev/xvdn' '/dev/xvdo' '/dev/xvdp' '/dev/xvdq' '/dev/xvdr' '/dev/xvds' '/dev/xvdt' '/dev/xvdu' '/dev/xvdv' '/dev/xvdw' '/dev/xvdx' '/dev/xvdy' '/dev/xvdz')
-      for device in ${deviceslist[@]}; do
-          if ([ -b $device ]) then
-              actual_devices=( "${actual_devices[@]}" $device )
-          fi
-      done
+      if [[ "${cell_backend}" == "aws" ]]; then
+        deviceslist=('/dev/xvdb' '/dev/xvdc' '/dev/xvdd' '/dev/xvde' '/dev/xvdf' '/dev/xvdg' '/dev/xvdh' '/dev/xvdi' '/dev/xvdj' '/dev/xvdk' '/dev/xvdl' '/dev/xvdm' '/dev/xvdn' '/dev/xvdo' '/dev/xvdp' '/dev/xvdq' '/dev/xvdr' '/dev/xvds' '/dev/xvdt' '/dev/xvdu' '/dev/xvdv' '/dev/xvdw' '/dev/xvdx' '/dev/xvdy' '/dev/xvdz')
+        for device in ${deviceslist[@]}; do
+            if ([ -b $device ]) then
+                actual_devices=( "${actual_devices[@]}" $device )
+            fi
+        done
 
-      n=0
-      for device in "${actual_devices[@]}"; do
-          n=`expr $n + 1`
-          if [ ! -b ${device}1 ]; then
-              echo "Creating partition on ${device}" >&2
-              parted -s -a optimal $device mklabel gpt -- mkpart primary xfs 1 -1 >&2
-              partprobe $device >&2 || true
-              mkfs.xfs ${device}1 >&2 || true
-          fi
-          if mountpoint -q -- "/mnt/data_${n}"; then
-              echo "/mnt/data_${n} is already mounted" >&2
-          else
+        n=0
+        for device in "${actual_devices[@]}"; do
+            n=`expr $n + 1`
+            if [ ! -b ${device}1 ]; then
+                echo "Creating partition on ${device}" >&2
+                parted -s -a optimal $device mklabel gpt -- mkpart primary xfs 1 -1 >&2
+                partprobe $device >&2 || true
+                mkfs.xfs ${device}1 >&2 || true
+            fi
+            if mountpoint -q -- "/mnt/data_${n}"; then
+                echo "/mnt/data_${n} is already mounted" >&2
+            else
               echo "/mnt/data_${n} is not a mountpoint" >&2
-              mkdir -p -m 755 /mnt/data_${n} >&2
-              mount ${device}1 /mnt/data_${n} >&2 || true
-              echo "${device}1 /mnt/data_${n} xfs rw,relatime,attr2,inode64,noquota,nofail 0 0" >> /etc/fstab
-          fi
+                mkdir -p -m 755 /mnt/data_${n} >&2
+                mount ${device}1 /mnt/data_${n} >&2 || true
+                echo "${device}1 /mnt/data_${n} xfs rw,relatime,attr2,inode64,noquota,nofail 0 0" >> /etc/fstab
+            fi
 
-          mkdir -p -m 755 /mnt/data_${n}/{hadoop_data,kafka_data}
-          chown -R hadoop:hadoop /mnt/data_${n}/{hadoop_data,kafka_data}
-      done
-      echo $n
+            mkdir -p -m 755 /mnt/data_${n}/{hadoop_data,kafka_data}
+            chown -R hadoop:hadoop /mnt/data_${n}/{hadoop_data,kafka_data}
+        done
+        echo $n
+      fi
   - path: /usr/local/bin/get_ip
     owner: 'root:root'
     permissions: '0755'
     content: |
-      #!/bin/sh
+      #!/bin/bash
+      #gets the local machine ip
       source /etc/profile.d/cellos.sh
-      set -o nounset -o errexit
-      if [ -e /etc/environment ]
-      then
-        set -o allexport
-        source /etc/environment
-        set +o allexport
+
+      if [[ "$cell_backend" == "aws" ]]; then
+        echo $(curl -fsSL http://169.254.169.254/latest/meta-data/local-ipv4)
       fi
-
-      get_private_ip() {
-          curl -fsSL http://169.254.169.254/latest/meta-data/local-ipv4
-      }
-
-      echo $(get_private_ip)
   - path: /usr/local/bin/report_status
     owner: 'root:root'
     permissions: '0755'
     content: |
       #!/bin/bash
-
+      #copies an updated status file in a central location
       source /etc/profile.d/cellos.sh
       mkdir -p /opt/cell/status
 
@@ -222,7 +196,7 @@ write_files:
 
       echo -e "${message} ${ts}" | tee -a $status_file
       
-      aws s3 cp $status_file s3://${cell_bucket_name}/${full_cell_name}/shared/status/${instance_id} \
+      filetool --put $status_file /shared/status/${instance_id} \
           --metadata-directive REPLACE --cache-control max-age=0,public \
           --expires 2000-01-01T00:00:00Z &>/dev/null
   - path: /usr/local/bin/yaml2json
@@ -230,6 +204,7 @@ write_files:
     permissions: '0755'
     content: |
       #!/bin/bash
+      #transforms yaml file (stdin) to json(stdout)
       set -o pipefail
 
       python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' | cat "$@"
@@ -249,7 +224,133 @@ write_files:
       source /etc/profile.d/cellos.sh
       role=$1
       index=$(( $2 - 1 ))
-      [[ "$3" == "ip" ]] && ret=0
-      [[ "$3" == "host" ]] && ret=1
-      machine=$(aws --region ${aws_region} ec2 describe-instances --query 'Reservations[*].Instances[*].[PrivateIpAddress, PrivateDnsName]' --filters Name=instance-state-code,Values=16 Name=tag:cell,Values=${cell_name} Name=tag:role,Values=${role} | jq -r ".[0][${index}][${ret}]")
-      echo $machine
+      if [[ "$cell_backend" == "aws" ]]; then
+        [[ "$3" == "ip" ]] && ret=0
+        [[ "$3" == "host" ]] && ret=1
+        machine=$(aws --region ${aws_region} ec2 describe-instances --query 'Reservations[*].Instances[*].[PrivateIpAddress, PrivateDnsName]' --filters Name=instance-state-code,Values=16 Name=tag:cell,Values=${cell_name} Name=tag:role,Values=${role} | jq -r ".[0][${index}][${ret}]")
+        echo $machine
+        fi
+  - path: /usr/local/bin/error_exit
+    owner: 'root:root'
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      source /etc/profile.d/cellos.sh
+      [[ "${cell_backend}" == "aws" ]] && cfn-signal -e 1 -r "$1" "$aws_wait_handle"
+      exit 1
+  - path: /usr/local/bin/success_exit
+    owner: 'root:root'
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      source /etc/profile.d/cellos.sh
+      [[ $cell_backend == "aws" ]] && cfn-signal -e 0 -r "Stack setup complete" "${aws_wait_handle}"
+      exit 0
+  - path: /usr/local/bin/pathtool
+    owner: 'root:root'
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      #displays the central shared location path
+      source /etc/profile.d/cellos.sh
+      path=$1
+      [[ "${cell_backend}" == "aws" ]] && echo -n "s3://${cell_bucket_name}/${full_cell_name}${path}"
+  - path: /usr/local/bin/filetool
+    owner: 'root:root'
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      #implements operations on the central shared file location: get, put, sync, touch; transforms logical paths to physical paths 
+      source /etc/profile.d/cellos.sh
+      case "$1" in
+        --touch)
+          dest=$2
+          [[ "${cell_backend}" == "aws" ]] && aws s3api put-object --bucket ${cell_bucket_name} --key ${full_cell_name}${dest}
+        ;;
+        --sync)
+          src=$2
+          full_dest=$3
+          [[ "${cell_backend}" == "aws" ]] && aws s3 sync --delete "${src}" "${full_dest}"
+        ;;
+        --count)
+          path=$2
+          [[ "${cell_backend}" == "aws" ]] && aws s3api list-objects --bucket ${cell_bucket_name} --prefix ${full_cell_name}${path} | jq -r '.Contents | length'
+        ;;
+        --put)
+          shift; src=$1
+          shift; dest=$1
+          shift
+          [[ "${cell_backend}" == "aws" ]] && aws s3 cp ${src} s3://${cell_bucket_name}/${full_cell_name}${dest} "$@"
+          [[ "${cell_backend}" == "azure" ]] && cp -a ${src} /cell${dest}
+        ;;
+        --get)
+          src=$2
+          dest=$3
+          [[ "${cell_backend}" == "aws" ]] && aws s3 cp s3://${cell_bucket_name}/${full_cell_name}${src} ${dest}
+        ;;
+        *)
+        echo "filetool [--sync|--touch] [src] [dest]"
+        exit 1
+        ;;
+      esac
+  - path: /usr/local/bin/prepare_aws
+    owner: 'root:root'
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      source /etc/profile.d/cellos.sh
+      curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
+      cat >> awslogs.conf <<-EOT
+      [general]
+      state_file = /var/awslogs/state/agent-state
+
+      [/var/log/cloud-init-output.log]
+      datetime_format = %Y-%m-%d %H:%M:%S
+      file = /var/log/cloud-init-output.log
+      buffer_duration = 5000
+      log_stream_name = ${full_cell_name}
+      initial_position = start_of_file
+      log_group_name = /var/log/cloud-init-output.log
+      EOT
+
+      python ./awslogs-agent-setup.py -r ${aws_region} -n -c awslogs.conf
+  - path: /usr/local/bin/prepare_seeds
+    owner: 'root:root'
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      #sets up the seed and provisioning folder (/opt/cell)
+      #copies the seed profile, versions bundle from the central shared location
+      source /etc/profile.d/cellos.sh
+      mkdir -p /opt/cell/etc/roles /opt/cell/cluster/puppet/modules /opt/cell/puppet/profiles /opt/cell/seed
+      download_cell_profile() {
+        AWS_ACCESS_KEY_ID="${SAASBASE_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${SAASBASE_SECRET_ACCESS_KEY}" aws s3 cp ${repository}/cell-os/${cellos_version}.yaml /opt/cell/puppet/profiles
+        # attempt to override the profile from the local bucket
+        filetool --get /shared/cell-os/${cellos_version}.yaml /opt/cell/puppet/profiles/
+        echo ${cellos_version} > /opt/cell/cluster/profile
+        touch /opt/cell/cluster/cluster.yaml
+      }
+      # download cell profile so we can get the saasbase installer version
+      download_cell_profile
+      touch /opt/cell/etc/roles/${cell_role}
+      saasbase_version=$(cat /opt/cell/puppet/profiles/${cellos_version}.yaml | yaml2json | jq -r '.["saasbase_deployment::version"]')
+      echo "export saasbase_version=${saasbase_version}" >> /etc/profile.d/cellos.sh
+      # download sb installer
+      curl -o /usr/local/bin/saasbase_installer https://s3.amazonaws.com/${repository:5}/saasbase_installer${saasbase_version}
+      chmod +x /usr/local/bin/saasbase_installer
+
+      AWS_ACCESS_KEY_ID="${SAASBASE_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${SAASBASE_SECRET_ACCESS_KEY}" bash /usr/local/bin/saasbase_installer -d /opt/cell fetch ${saasbase_version}
+      download_cell_profile
+
+      AWS_ACCESS_KEY_ID="${SAASBASE_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${SAASBASE_SECRET_ACCESS_KEY}" aws s3 cp ${repository}/cell-os/seed-${cellos_version}.tar.gz /opt/cell
+      # attempt to download seed from local bucket as well
+      filetool --get /shared/cell-os/seed.tar.gz /opt/cell/
+      # unarchive files
+      mkdir -p /opt/cell/seed
+      pushd /opt/cell
+      rm -rf seed
+      [[ -f seed-${cellos_version}.tar.gz ]] && tar zxf seed-${cellos_version}.tar.gz
+      [[ -f seed.tar.gz ]] && tar zxf seed.tar.gz
+      rm -rf seed*.tar.gz
+      popd
+    
